# Generated by Django 5.0 on 2023-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
