# Generated by Django 5.0 on 2024-03-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_task_alter_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='Price',
        ),
    ]
