# Generated by Django 5.0 on 2024-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_category_menu_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
