# Generated by Django 5.0 on 2024-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Cashier', 'Cashier'), ('Manager', 'Manager')], default='Cashier', max_length=100),
        ),
    ]
