# Generated by Django 5.0 on 2024-03-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_address_user_bank_account_number_user_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('In_progress', 'In Progress'), ('Done', 'Done')], default='Todo', max_length=20),
        ),
    ]
