# Generated by Django 5.0 on 2024-03-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
